-- LUPENREIN KI Vertrieb V4 – Supabase/PostgreSQL schema
-- In Supabase unter SQL Editor ausführen.

create table if not exists leads (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  company text not null,
  city text not null,
  sector text not null,
  score integer not null default 0 check (score between 0 and 100),
  service text not null,
  status text not null default 'Neu',
  contact text,
  email text,
  phone text,
  website text,
  address text,
  source text,
  source_id text,
  reason text,
  potential text,
  analysis jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists activities (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint not null references leads(id) on delete cascade,
  type text not null,
  direction text not null default 'intern',
  content text not null,
  outcome text,
  created_at timestamptz not null default now()
);

create index if not exists leads_owner_idx on leads(owner_id);
create index if not exists leads_status_idx on leads(owner_id,status);
create index if not exists leads_score_idx on leads(owner_id,score desc);
create index if not exists leads_sector_idx on leads(owner_id,sector);
create index if not exists activities_lead_idx on activities(owner_id,lead_id,created_at desc);
create unique index if not exists leads_owner_source_unique_idx on leads(owner_id,source_id) where source_id is not null;

alter table leads enable row level security;
alter table activities enable row level security;

-- Jeder angemeldete Benutzer sieht und verändert nur seine eigenen Daten.
drop policy if exists "leads_select_own" on leads;
create policy "leads_select_own" on leads for select using (auth.uid() = owner_id);
drop policy if exists "leads_insert_own" on leads;
create policy "leads_insert_own" on leads for insert with check (auth.uid() = owner_id);
drop policy if exists "leads_update_own" on leads;
create policy "leads_update_own" on leads for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "leads_delete_own" on leads;
create policy "leads_delete_own" on leads for delete using (auth.uid() = owner_id);

drop policy if exists "activities_select_own" on activities;
create policy "activities_select_own" on activities for select using (auth.uid() = owner_id);
drop policy if exists "activities_insert_own" on activities;
create policy "activities_insert_own" on activities for insert with check (auth.uid() = owner_id);
drop policy if exists "activities_update_own" on activities;
create policy "activities_update_own" on activities for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "activities_delete_own" on activities;
create policy "activities_delete_own" on activities for delete using (auth.uid() = owner_id);

-- V5: Kommunikationszentrale
create table if not exists messages (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint not null references leads(id) on delete cascade,
  to_email text not null,
  subject text not null,
  body text not null,
  status text not null default 'Entwurf',
  provider text not null default 'preview',
  ai_mode text not null default 'local',
  sent_at timestamptz,
  reply_text text,
  reply_intent text,
  reply_summary text,
  follow_up_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists messages_owner_idx on messages(owner_id,created_at desc);
create index if not exists messages_lead_idx on messages(owner_id,lead_id,created_at desc);
create index if not exists messages_followup_idx on messages(owner_id,follow_up_at) where follow_up_at is not null;
alter table messages enable row level security;
drop policy if exists "messages_select_own" on messages;
create policy "messages_select_own" on messages for select using (auth.uid() = owner_id);
drop policy if exists "messages_insert_own" on messages;
create policy "messages_insert_own" on messages for insert with check (auth.uid() = owner_id);
drop policy if exists "messages_update_own" on messages;
create policy "messages_update_own" on messages for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "messages_delete_own" on messages;
create policy "messages_delete_own" on messages for delete using (auth.uid() = owner_id);

-- V6: Aufgaben, Termine und Gmail-Metadaten
alter table messages add column if not exists gmail_draft_id text;
alter table messages add column if not exists gmail_message_id text;

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint not null references leads(id) on delete cascade,
  title text not null,
  type text not null default 'Follow-up',
  due_at timestamptz not null,
  status text not null default 'Offen',
  note text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);
create index if not exists tasks_owner_due_idx on tasks(owner_id,status,due_at);
create index if not exists tasks_lead_idx on tasks(owner_id,lead_id,due_at);
alter table tasks enable row level security;
drop policy if exists "tasks_select_own" on tasks;
create policy "tasks_select_own" on tasks for select using (auth.uid() = owner_id);
drop policy if exists "tasks_insert_own" on tasks;
create policy "tasks_insert_own" on tasks for insert with check (auth.uid() = owner_id);
drop policy if exists "tasks_update_own" on tasks;
create policy "tasks_update_own" on tasks for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "tasks_delete_own" on tasks;
create policy "tasks_delete_own" on tasks for delete using (auth.uid() = owner_id);

-- V7: Angebote, Kalkulation und Auftragsabschluss
create table if not exists offers (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint not null references leads(id) on delete cascade,
  number text not null,
  title text not null,
  status text not null default 'Entwurf',
  valid_until date not null,
  items jsonb not null default '[]'::jsonb,
  notes text,
  subtotal_one_time numeric(12,2) not null default 0,
  subtotal_monthly numeric(12,2) not null default 0,
  vat_rate numeric(5,2) not null default 19,
  sent_at timestamptz,
  accepted_at timestamptz,
  declined_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists offers_owner_number_idx on offers(owner_id,number);
create index if not exists offers_lead_idx on offers(owner_id,lead_id,created_at desc);
create index if not exists offers_status_idx on offers(owner_id,status,created_at desc);
alter table offers enable row level security;
drop policy if exists "offers_select_own" on offers;
create policy "offers_select_own" on offers for select using (auth.uid() = owner_id);
drop policy if exists "offers_insert_own" on offers;
create policy "offers_insert_own" on offers for insert with check (auth.uid() = owner_id);
drop policy if exists "offers_update_own" on offers;
create policy "offers_update_own" on offers for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "offers_delete_own" on offers;
create policy "offers_delete_own" on offers for delete using (auth.uid() = owner_id);

-- V8: Objektbesichtigungen, Kalkulationsgrundlage und Angebotsversand
create table if not exists surveys (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint not null references leads(id) on delete cascade,
  status text not null default 'Entwurf',
  object_name text not null,
  object_type text,
  address text,
  area_sqm numeric(12,2) not null default 0,
  frequency_per_week numeric(8,2) not null default 0,
  hours_per_visit numeric(8,2) not null default 0,
  workers integer not null default 1,
  window_area_sqm numeric(12,2) not null default 0,
  restrooms integer not null default 0,
  kitchens integer not null default 0,
  floor_type text,
  access_window text,
  start_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists surveys_lead_idx on surveys(owner_id,lead_id,created_at desc);
alter table surveys enable row level security;
drop policy if exists "surveys_select_own" on surveys;
create policy "surveys_select_own" on surveys for select using (auth.uid() = owner_id);
drop policy if exists "surveys_insert_own" on surveys;
create policy "surveys_insert_own" on surveys for insert with check (auth.uid() = owner_id);
drop policy if exists "surveys_update_own" on surveys;
create policy "surveys_update_own" on surveys for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "surveys_delete_own" on surveys;
create policy "surveys_delete_own" on surveys for delete using (auth.uid() = owner_id);

alter table offers add column if not exists survey_id bigint references surveys(id) on delete set null;
alter table offers add column if not exists gmail_draft_id text;
create index if not exists offers_survey_idx on offers(owner_id,survey_id) where survey_id is not null;

-- V9: Kundenobjekte, Vertragsdaten und Umsatzbasis
create table if not exists customer_objects (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  lead_id bigint not null references leads(id) on delete cascade,
  offer_id bigint not null references offers(id) on delete restrict,
  survey_id bigint references surveys(id) on delete set null,
  status text not null default 'Geplant',
  object_name text not null,
  object_type text,
  address text,
  service text,
  start_date date,
  area_sqm numeric(12,2) not null default 0,
  frequency_per_week numeric(8,2) not null default 0,
  monthly_revenue numeric(12,2) not null default 0,
  one_time_revenue numeric(12,2) not null default 0,
  contract_term_months integer not null default 12,
  notice_period_months integer not null default 3,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists customer_objects_offer_unique_idx on customer_objects(owner_id,offer_id);
create index if not exists customer_objects_status_idx on customer_objects(owner_id,status,start_date);
create index if not exists customer_objects_lead_idx on customer_objects(owner_id,lead_id,created_at desc);
alter table customer_objects enable row level security;
drop policy if exists "customer_objects_select_own" on customer_objects;
create policy "customer_objects_select_own" on customer_objects for select using (auth.uid() = owner_id);
drop policy if exists "customer_objects_insert_own" on customer_objects;
create policy "customer_objects_insert_own" on customer_objects for insert with check (auth.uid() = owner_id);
drop policy if exists "customer_objects_update_own" on customer_objects;
create policy "customer_objects_update_own" on customer_objects for update using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
drop policy if exists "customer_objects_delete_own" on customer_objects;
create policy "customer_objects_delete_own" on customer_objects for delete using (auth.uid() = owner_id);

-- V10: Rollen, Audit und KI-Vertriebsagent
create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'sales' check (role in ('admin','sales','ops','read_only')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table profiles enable row level security;
drop policy if exists "profiles_select_own" on profiles;
create policy "profiles_select_own" on profiles for select using (auth.uid() = user_id);
drop policy if exists "profiles_update_own" on profiles;
-- Rollen werden bewusst nur administrativ (SQL/Service Role) geändert, damit niemand sich selbst hochstuft.

create or replace function public.handle_new_user_profile() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(user_id,email,display_name,role)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'name',new.email),'sales')
  on conflict (user_id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile after insert on auth.users for each row execute procedure public.handle_new_user_profile();

-- Backfill für Benutzer, die schon vor V10 existierten.
insert into public.profiles(user_id,email,display_name,role)
select id,email,coalesce(raw_user_meta_data->>'name',email),'sales' from auth.users
on conflict (user_id) do nothing;

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_owner_idx on audit_logs(owner_id,created_at desc);
alter table audit_logs enable row level security;
drop policy if exists "audit_logs_select_own" on audit_logs;
create policy "audit_logs_select_own" on audit_logs for select using (auth.uid() = owner_id);
drop policy if exists "audit_logs_insert_own" on audit_logs;
create policy "audit_logs_insert_own" on audit_logs for insert with check (auth.uid() = owner_id);

create table if not exists agent_runs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  status text not null,
  leads_reviewed integer not null default 0,
  tasks_created integer not null default 0,
  hot_leads integer not null default 0,
  summary text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists agent_runs_owner_idx on agent_runs(owner_id,started_at desc);
alter table agent_runs enable row level security;
drop policy if exists "agent_runs_select_own" on agent_runs;
create policy "agent_runs_select_own" on agent_runs for select using (auth.uid() = owner_id);
drop policy if exists "agent_runs_insert_own" on agent_runs;
create policy "agent_runs_insert_own" on agent_runs for insert with check (auth.uid() = owner_id);

-- Nach dem ersten produktiven Benutzer kann dessen Rolle einmalig auf admin gesetzt werden:
-- update profiles set role='admin' where email='IHRE-ADMIN-EMAIL';
