import Link from 'next/link'
import {getCustomerObjects,getLeads,getMessages,getOffers,getTasks} from '@/lib/store'
export default async function Dashboard(){
 const [leads,messages,tasks,offers,objects]=await Promise.all([getLeads(),getMessages(),getTasks({status:'Offen'}),getOffers(),getCustomerObjects()])
 const offerOpen=offers.filter(o=>['Entwurf','Versendet'].includes(o.status));const offerWon=offers.filter(o=>o.status==='Angenommen');const hot=leads.filter(l=>l.score>=85);const replies=messages.filter(m=>m.status==='Beantwortet');const interested=leads.filter(l=>l.status==='Interessiert');const customers=leads.filter(l=>l.status==='Kunde');const todayEnd=new Date();todayEnd.setHours(23,59,59,999);const dueToday=tasks.filter(t=>new Date(t.dueAt)<=todayEnd)
 const activeObjects=objects.filter(o=>o.status==='Aktiv');const mrr=activeObjects.reduce((s,o)=>s+o.monthlyRevenue,0);const euro=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n)
 return <>
  <section className="hero"><div><span className="eyebrow">V10 · VERTRIEBSÜBERSICHT</span><h2>Guten Tag, LUPENREIN.</h2><p>Leads, Antworten und nächste Schritte in einer gemeinsamen Vertriebssteuerung.</p></div><Link href="/lead-finder" className="primary">+ Leads finden</Link></section>
  <section className="metrics">{[[String(leads.length),'Leads gesamt','im CRM'],[String(hot.length),'Heiße Leads','Score ≥ 85'],[String(replies.length),'Antworten','klassifiziert'],[String(dueToday.length),'Heute fällig','Aufgaben'],[String(offerOpen.length),'Offene Angebote','nachfassen'],[String(customers.length),'Kunden','gewonnen'],[euro(mrr),'MRR','aktive Objekte']].map(([n,l,s])=><div className="metric" key={l}><span>{l}</span><strong>{n}</strong><small>{s}</small></div>)}</section>
  <div className="grid2">
   <section className="panel"><div className="panelHead"><div><span className="eyebrow">KI-PRIORISIERUNG</span><h3>Beste Chancen</h3></div><Link href="/leads">Alle Leads →</Link></div><div className="leadTable"><div className="tableHead"><span>Unternehmen</span><span>Branche</span><span>Leistung</span><span>Score</span></div>{hot.slice(0,5).map(l=><Link className="tableRow" href={`/leads/${l.id}`} key={l.id}><span><b>{l.company}</b><small>{l.city}</small></span><span>{l.sector}</span><span>{l.service}</span><span className="score">{l.score}</span></Link>)}{!hot.length&&<div className="emptyState">Noch keine heißen Leads.</div>}</div></section>
   <section className="panel"><div className="panelHead"><div><span className="eyebrow">HEUTE ZU ERLEDIGEN</span><h3>Nächste Schritte</h3></div><Link href="/tasks">Alle Aufgaben →</Link></div>{dueToday.slice(0,6).map(t=>{const l=leads.find(x=>x.id===t.leadId);return <div className="taskRow compact" key={t.id}><div><span className="taskType">{t.type}</span><b>{t.title}</b><small>{l?.company||'Lead'} · {new Date(t.dueAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}</small></div><Link href={`/leads/${t.leadId}`}>Öffnen →</Link></div>})}{!dueToday.length&&<div className="emptyState">Heute ist nichts überfällig oder fällig.</div>}</section>
  </div>
  <section className="panel"><div className="panelHead"><div><span className="eyebrow">PIPELINE</span><h3>Von Lead zu Kunde</h3></div><Link href="/pipeline">Pipeline öffnen →</Link></div><div className="funnel">{['Neu','Qualifiziert','Kontaktiert','Interessiert','Besichtigung','Angebot','Kunde'].map((s,i)=><div key={s} className="funnelStep"><span>{s}</span><b>{leads.filter(l=>l.status===s).length}</b><small>{i<6?'→':''}</small></div>)}</div><p className="dashboardHint">Aktuell interessiert: <b>{interested.length}</b> · Offene Aufgaben: <b>{tasks.length}</b> · Gewonnene Angebote: <b>{offerWon.length}</b> · <Link href="/offers">Angebote öffnen →</Link></p></section>
 </>
}
