'use client'
import {useState} from 'react'
const SERVICE_TYPES=['Unterhaltsreinigung','Büroreinigung','Glasreinigung','Bauendreinigung / Baureinigung','Industriereinigung'],WEEKDAYS=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'],FLOORS=['Teppich','PVC / Vinyl','Fliesen','Naturstein','Parkett / Holz','Industrieboden'],AREAS=['Büros','Flure','Empfang','Besprechungsräume','Lager','Produktion','Sozialräume']
export default function CustomerQuestionnaireWizard(){const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState<any>(null);const [v,setV]=useState<any>({company:'',contactName:'',email:'',phone:'',objectType:'Büro',address:'',areaSqm:0,serviceTypes:['Unterhaltsreinigung'],weekdays:[],frequency:'2× pro Woche',timeWindow:'Werktags ab 18:00 Uhr',floorTypes:[],areas:[],restrooms:0,kitchens:0,glassAreaSqm:0,staircases:0,elevators:0,specialAreas:'',soilLevel:'normal',materials:'LUPENREIN',access:'',specialRequests:'',desiredStart:''});const set=(k:string,x:any)=>setV((p:any)=>({...p,[k]:x}));const toggle=(k:string,x:string)=>set(k,v[k].includes(x)?v[k].filter((y:string)=>y!==x):[...v[k],x]);async function submit(){setBusy(true);setError('');const r=await fetch('/api/public/questionnaire',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(v)});const j=await r.json();setBusy(false);if(!r.ok)return setError(j.error||'Bitte prüfen Sie Ihre Angaben.');setDone(j)}
 if(done)return <main className="publicShell"><div className="publicCard successCard"><img src="/lupenrein-logo.png" alt="LUPENREIN"/><span className="successMark">✓</span><h1>Vielen Dank für Ihre Anfrage</h1><p>{done.mode==='instant'?'Ihr persönliches Angebot ist bereits fertig.':'Wir prüfen die Besonderheiten Ihres Objekts und melden uns kurzfristig mit dem finalen Angebot.'}</p>{done.offerUrl&&<a className="primary publicCta" href={done.offerUrl}>Angebot ansehen</a>}</div></main>
 const choices=(items:string[],key:string)=><div className="choiceGrid">{items.map(x=><button type="button" key={x} className={v[key].includes(x)?'choice active':'choice'} onClick={()=>toggle(key,x)}>{x}</button>)}</div>;return <main className="publicShell"><div className="publicCard"><header className="publicBrand"><img src="/lupenrein-logo.png" alt="LUPENREIN Gebäudereinigung"/><span>Kostenlose Objektanfrage</span></header><div className="progress"><i style={{width:`${(step+1)/5*100}%`}}/></div><p className="stepLabel">Schritt {step+1} von 5</p>
 {step===0&&<section><h1>Wie dürfen wir Sie erreichen?</h1><p>In wenigen Schritten zu Ihrem passenden Reinigungskonzept.</p><div className="formGrid"><label>Unternehmen / Name<input value={v.company} onChange={e=>set('company',e.target.value)} required/></label><label>Ansprechperson<input value={v.contactName} onChange={e=>set('contactName',e.target.value)}/></label><label>E-Mail<input type="email" value={v.email} onChange={e=>set('email',e.target.value)} required/></label><label>Telefon<input value={v.phone} onChange={e=>set('phone',e.target.value)}/></label></div></section>}
 {step===1&&<section><h1>Ihr Objekt</h1><div className="formGrid"><label>Objektart<input value={v.objectType} onChange={e=>set('objectType',e.target.value)} placeholder="z. B. Büro, Praxis, Halle"/></label><label>Fläche in m²<input type="number" min="1" value={v.areaSqm} onChange={e=>set('areaSqm',Number(e.target.value))}/></label><label className="wide">Vollständige Adresse<input value={v.address} onChange={e=>set('address',e.target.value)}/></label></div><h3>Gewünschte Leistungsarten</h3>{choices([...SERVICE_TYPES],'serviceTypes')}</section>}
 {step===2&&<section><h1>Wann soll gereinigt werden?</h1><label>Häufigkeit<select value={v.frequency} onChange={e=>set('frequency',e.target.value)}><option>einmalig</option><option>1× pro Woche</option><option>2× pro Woche</option><option>3× pro Woche</option><option>5× pro Woche</option><option>6× pro Woche</option><option>täglich</option></select></label><h3>Gewünschte Wochentage</h3>{choices(WEEKDAYS,'weekdays')}<label>Zeitfenster<input value={v.timeWindow} onChange={e=>set('timeWindow',e.target.value)}/></label><label>Gewünschter Start<input type="date" value={v.desiredStart} onChange={e=>set('desiredStart',e.target.value)}/></label></section>}
 {step===3&&<section><h1>Flächen und Bereiche</h1><h3>Bodenarten</h3>{choices(FLOORS,'floorTypes')}<h3>Räume / Bereiche</h3>{choices(AREAS,'areas')}<div className="formGrid compact"><label>Sanitärbereiche<input type="number" min="0" value={v.restrooms} onChange={e=>set('restrooms',Number(e.target.value))}/></label><label>Küchen / Teeküchen<input type="number" min="0" value={v.kitchens} onChange={e=>set('kitchens',Number(e.target.value))}/></label><label>Glasfläche m²<input type="number" min="0" value={v.glassAreaSqm} onChange={e=>set('glassAreaSqm',Number(e.target.value))}/></label><label>Treppenhäuser<input type="number" min="0" value={v.staircases} onChange={e=>set('staircases',Number(e.target.value))}/></label><label>Aufzüge<input type="number" min="0" value={v.elevators} onChange={e=>set('elevators',Number(e.target.value))}/></label><label>Sonderflächen<input value={v.specialAreas} onChange={e=>set('specialAreas',e.target.value)} placeholder="Labor, Reinraum …"/></label></div></section>}
 {step===4&&<section><h1>Fast geschafft</h1><div className="formGrid"><label>Verschmutzungsgrad<select value={v.soilLevel} onChange={e=>set('soilLevel',e.target.value)}><option value="leicht">Leicht</option><option value="normal">Normal</option><option value="stark">Stark</option></select></label><label>Materialstellung<select value={v.materials} onChange={e=>set('materials',e.target.value)}><option>LUPENREIN</option><option>Kunde</option><option>gemischt</option></select></label><label className="wide">Zugang / Schlüssel<textarea value={v.access} onChange={e=>set('access',e.target.value)} rows={2}/></label><label className="wide">Besondere Wünsche<textarea value={v.specialRequests} onChange={e=>set('specialRequests',e.target.value)} rows={3}/></label></div><div className="privacyNote">Ihre Angaben werden ausschließlich zur Erstellung und Bearbeitung Ihres Angebots verwendet. Interne Kalkulationsgrundlagen sind niemals Bestandteil Ihrer Ansicht.</div></section>}
 {error&&<p className="actionNotice">{error}</p>}<footer className="wizardNav">{step>0&&<button className="secondary" onClick={()=>setStep(step-1)}>Zurück</button>}<span/>{step<4?<button className="primary" disabled={(step===0&&(!v.company||!v.email))||(step===1&&(!v.address||v.areaSqm<=0))} onClick={()=>setStep(step+1)}>Weiter</button>:<button className="primary" disabled={busy} onClick={submit}>{busy?'Wird erstellt …':'Anfrage absenden'}</button>}</footer></div></main>}

