'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import {STATUSES,type LeadStatus} from '@/lib/types'
export default function LeadActions({leadId,status,hasWebsite}:{leadId:string,status:LeadStatus,hasWebsite:boolean}){
  const router=useRouter();const [text,setText]=useState('');const [mode,setMode]=useState('');const [busy,setBusy]=useState(false);const [analyzing,setAnalyzing]=useState(false);const [notice,setNotice]=useState('')
  async function createMessage(){setBusy(true);setNotice('');const r=await fetch('/api/messages/draft',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({leadId})});const j=await r.json();setBusy(false);if(!r.ok){setNotice(j.error||'Entwurf konnte nicht erstellt werden.');return}setText(j.message?.body||'');setMode(j.message?.aiMode||'');setNotice('Entwurf gespeichert. Du findest ihn auch in der Nachrichten-Zentrale.');router.refresh()}
  async function analyze(){setAnalyzing(true);setNotice('');const r=await fetch(`/api/leads/${leadId}/analyze`,{method:'POST'});const j=await r.json();setAnalyzing(false);if(!r.ok){setNotice(j.error||'Analyse fehlgeschlagen.');return}setNotice(j.analysis?.mode==='ai'?'Website mit KI analysiert und Lead aktualisiert.':'Website analysiert und Lead aktualisiert.');router.refresh()}
  async function setStatus(v:string){await fetch(`/api/leads/${leadId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status:v})});router.refresh()}
  return <div className="leadActions"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><button className="secondary wide" onClick={analyze} disabled={analyzing||!hasWebsite}>{analyzing?'Website wird analysiert …':hasWebsite?'Website analysieren':'Keine Website hinterlegt'}</button><button className="primary wide" onClick={createMessage} disabled={busy}>{busy?'Erstelle Vorschlag …':'KI-Kontaktvorschlag erstellen'}</button>{notice&&<div className="actionNotice">{notice}</div>}{text&&<div className="messageDraft"><div><span className="eyebrow">ENTWURF</span><small>{mode==='ai'?'KI generiert':'Lokale Vorschau'}</small></div><textarea value={text} onChange={e=>setText(e.target.value)} rows={12}/><button className="secondary" onClick={()=>navigator.clipboard.writeText(text)}>Text kopieren</button></div>}</div>
}
