'use client'
import {useMemo,useState} from 'react'
import {useRouter} from 'next/navigation'
import type {Lead,Message} from '@/lib/types'

type Props={messages:Message[];leads:Lead[];webhookConfigured:boolean;gmailConfigured:boolean}
const intentLabel:Record<string,string>={interessiert:'Interessiert',später:'Später erneut melden',kein_interesse:'Kein Interesse','rückfrage':'Rückfrage',neutral:'Neutral',unbekannt:'Unbekannt'}
export default function MessageCenter({messages,leads,webhookConfigured,gmailConfigured}:Props){
 const router=useRouter();const [activeId,setActiveId]=useState(messages[0]?.id||'');const [busy,setBusy]=useState('');const [notice,setNotice]=useState('');
 const active=messages.find(x=>x.id===activeId)||messages[0];const leadMap=useMemo(()=>Object.fromEntries(leads.map(l=>[l.id,l])),[leads]);
 async function call(url:string,body?:any){setBusy(url);setNotice('');const r=await fetch(url,{method:'POST',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const j=await r.json();setBusy('');if(!r.ok){setNotice(j.error||'Aktion fehlgeschlagen.');return null}router.refresh();return j}
 async function saveDraft(){if(!active)return;const subject=(document.getElementById('msgSubject') as HTMLInputElement)?.value||'';const body=(document.getElementById('msgBody') as HTMLTextAreaElement)?.value||'';const to=(document.getElementById('msgTo') as HTMLInputElement)?.value||'';setBusy('save');const r=await fetch(`/api/messages/${active.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({subject,body,to})});const j=await r.json();setBusy('');setNotice(r.ok?'Entwurf gespeichert.':j.error||'Speichern fehlgeschlagen.');router.refresh()}
 if(!messages.length)return <section className="empty panel"><div className="emptyIcon">✉</div><h3>Noch keine Nachrichten</h3><p>Öffne einen Lead mit E-Mail-Adresse und erstelle dort den ersten KI-Entwurf. Er erscheint danach hier zur Prüfung und Freigabe.</p></section>
 return <div className="messageLayout"><aside className="messageList panel"><div className="messageListHead"><span className="eyebrow">POSTAUSGANG & ANTWORTEN</span><b>{messages.length}</b></div>{messages.map(m=>{const l=leadMap[m.leadId];return <button className={`messageListItem ${active?.id===m.id?'active':''}`} key={m.id} onClick={()=>{setActiveId(m.id);setNotice('')}}><div><strong>{l?.company||'Lead'}</strong><span>{m.subject}</span></div><em className={`msgStatus ${m.status.toLowerCase()}`}>{m.status}</em><small>{new Date(m.createdAt).toLocaleDateString('de-DE')}</small></button>})}</aside>
 <section className="panel messageDetail">{active&&<><div className="messageDetailHead"><div><span className="eyebrow">{leadMap[active.leadId]?.company||'LEAD'}</span><h3>{active.subject}</h3></div><span className={`statusPill ${active.status.toLowerCase()}`}>{active.status}</span></div>
 <div className="deliveryInfo"><span>Versand: <b>{active.provider==='gmail'?'Gmail':active.provider==='webhook'?'Connector':'Vorschau'}</b></span><span>KI: <b>{active.aiMode==='ai'?'aktiv':'lokal'}</b></span>{active.sentAt&&<span>Gesendet: <b>{new Date(active.sentAt).toLocaleString('de-DE')}</b></span>}</div>
 {active.status==='Entwurf'?<div className="messageEditor"><label>An<input id="msgTo" defaultValue={active.to}/></label><label>Betreff<input id="msgSubject" defaultValue={active.subject}/></label><label>Nachricht<textarea id="msgBody" rows={14} defaultValue={active.body}/></label><div className="messageButtons"><button className="secondary" disabled={Boolean(busy)} onClick={saveDraft}>{busy==='save'?'Speichern …':'Entwurf speichern'}</button><button className="primary" disabled={Boolean(busy)} onClick={()=>call(`/api/messages/${active.id}/approve`)}>Freigeben</button></div></div>:<div className="mailPreview"><div><b>An:</b> {active.to}</div><div><b>Betreff:</b> {active.subject}</div><pre>{active.body}</pre></div>}
 {active.status==='Freigegeben'&&<div className="sendBox">{gmailConfigured?<><p>Gmail ist für die Web-App autorisiert. Erstelle zuerst einen Gmail-Entwurf; erst ein weiterer bewusster Klick versendet ihn.</p>{!active.gmailDraftId?<button className="primary" disabled={Boolean(busy)} onClick={()=>call(`/api/messages/${active.id}/gmail-draft`)}>In Gmail als Entwurf speichern</button>:<button className="primary" disabled={Boolean(busy)} onClick={()=>call(`/api/messages/${active.id}/gmail-send`)}>Gmail-Entwurf jetzt senden</button>}</>:<><p>{webhookConfigured?'Der Versand-Connector ist konfiguriert. Nach Klick wird die freigegebene Nachricht an den Connector übergeben.':'Kein Versand-Connector konfiguriert. Der Klick markiert die Nachricht im Vorschau-Modus als gesendet und aktualisiert die Pipeline.'}</p><button className="primary" disabled={Boolean(busy)} onClick={()=>call(`/api/messages/${active.id}/send`)}>{busy.includes('/send')?'Sende …':webhookConfigured?'Jetzt senden':'Als gesendet markieren'}</button></>}</div>}
 {(active.status==='Gesendet'||active.status==='Beantwortet')&&<ReplyBox message={active} busy={Boolean(busy)} onSubmit={(text)=>call(`/api/messages/${active.id}/reply`,{text})}/>} 
 {active.replyText&&<div className="replyResult"><span className="eyebrow">ANTWORT-INTELLIGENCE</span><div className="intentRow"><strong>{intentLabel[active.replyIntent||'unbekannt']}</strong>{active.followUpAt&&<span>Follow-up: {new Date(active.followUpAt).toLocaleDateString('de-DE')}</span>}</div><p>{active.replySummary}</p><blockquote>{active.replyText}</blockquote></div>}
 {notice&&<div className="actionNotice">{notice}</div>}</>}</section></div>
}
function ReplyBox({message,busy,onSubmit}:{message:Message;busy:boolean;onSubmit:(text:string)=>void}){const [text,setText]=useState('');return <div className="replyBox"><span className="eyebrow">EINGEHENDE ANTWORT</span><h4>Antwort analysieren</h4><p>Bis der Posteingang direkt verbunden ist, kannst du eine erhaltene Antwort hier einfügen. Die KI erkennt Absicht und nächsten Schritt.</p><textarea rows={5} value={text} onChange={e=>setText(e.target.value)} placeholder="Antwort des potenziellen Kunden …"/><button className="secondary" disabled={busy||!text.trim()} onClick={()=>onSubmit(text)}>Antwort klassifizieren</button></div>}
