'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import type {Lead,OfferItem,ServiceSpecificationItem,SiteSurvey} from '@/lib/types'
import {COMPANY_SERVICES} from '@/lib/company'
import ServiceSpecificationConfigurator from './ServiceSpecificationConfigurator'
export default function OfferCreator({leads,initialLeadId,survey}:{leads:Lead[];initialLeadId?:string;survey?:SiteSurvey}){
 const router=useRouter(),[leadId,setLeadId]=useState(initialLeadId||survey?.leadId||leads[0]?.id||''),[title,setTitle]=useState(survey?`Reinigungsangebot · ${survey.objectName}`:''),[validUntil,setValidUntil]=useState(new Date(Date.now()+14*86400000).toISOString().slice(0,10)),[lv,setLv]=useState<ServiceSpecificationItem[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [items,setItems]=useState<OfferItem[]>([{id:'1',service:'Unterhaltsreinigung',description:survey?`${survey.frequencyPerWeek}× wöchentlich · ${survey.areaSqm} m²`:'Regelmäßige Reinigung gemäß Leistungsverzeichnis',quantity:1,unit:'Monat',unitPrice:0,billing:'monatlich'}]),[notes,setNotes]=useState('Die angebotenen Leistungen erfolgen gemäß Absprache und beigefügtem Leistungsverzeichnis (LV).\n\nPreise verstehen sich netto zzgl. gesetzlicher MwSt. Leistungsbeginn nach gemeinsamer Abstimmung.')
 const patch=(i:number,p:Partial<OfferItem>)=>setItems(v=>v.map((x,n)=>n===i?{...x,...p}:x))
 async function save(){setBusy(true);setError('');const lead=leads.find(x=>x.id===leadId),r=await fetch('/api/offers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({leadId,surveyId:survey?.id,title:title||`Reinigungsangebot für ${lead?.company||''}`,validUntil,items,serviceSpecification:{version:1,items:lv},notes})}),j=await r.json();setBusy(false);if(!r.ok)return setError(j.error||'Fehler');router.push(`/offers/${j.offer.id}`);router.refresh()}
 return <section className="panel offerCreate"><div className="panelHead"><div><span className="eyebrow">NEUES ANGEBOT</span><h3>Kalkulation & Leistungsverzeichnis</h3></div></div>{survey&&<div className="surveySummary"><b>{survey.objectName}</b><span>{survey.areaSqm.toLocaleString('de-DE')} m² · {survey.frequencyPerWeek}×/Woche</span><small>{survey.address}</small></div>}<div className="offerFields"><label>Lead<select value={leadId} onChange={e=>setLeadId(e.target.value)}>{leads.map(x=><option key={x.id} value={x.id}>{x.company} · {x.city}</option>)}</select></label><label>Titel<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="z. B. Unterhaltsreinigung Bürostandort"/></label><label>Gültig bis<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label></div><div className="offerItems"><div className="offerItemHead"><span>Leistung</span><span>Beschreibung</span><span>Menge</span><span>Einheit</span><span>Preis netto</span><span>Rhythmus</span><span/></div>{items.map((x,i)=><div className="offerItemRow" key={x.id}><select value={x.service} onChange={e=>patch(i,{service:e.target.value})}>{COMPANY_SERVICES.map(s=><option key={s}>{s}</option>)}</select><input value={x.description||''} onChange={e=>patch(i,{description:e.target.value})}/><input type="number" min="0" value={x.quantity} onChange={e=>patch(i,{quantity:Number(e.target.value)})}/><input value={x.unit} onChange={e=>patch(i,{unit:e.target.value})}/><input type="number" min="0" step=".01" value={x.unitPrice} onChange={e=>patch(i,{unitPrice:Number(e.target.value)})}/><select value={x.billing} onChange={e=>patch(i,{billing:e.target.value as 'monatlich'|'einmalig'})}><option value="monatlich">monatlich</option><option value="einmalig">einmalig</option></select><button type="button" className="iconButton" onClick={()=>setItems(v=>v.filter((_,n)=>n!==i))} disabled={items.length===1}>×</button></div>)}</div><button type="button" className="secondary" onClick={()=>setItems(v=>[...v,{id:String(Date.now()),service:'Glasreinigung',description:'',quantity:1,unit:'Pauschale',unitPrice:0,billing:'einmalig'}])}>+ Position hinzufügen</button><ServiceSpecificationConfigurator value={lv} onChange={setLv}/><label className="offerNotes">Notizen / Bedingungen<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{error&&<p className="actionNotice">{error}</p>}<div className="offerSave"><button className="primary" onClick={save} disabled={busy||!leadId}>{busy?'Speichere …':'Angebot mit LV erstellen'}</button></div></section>
}

