'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import type {SelfServiceRequest} from '@/lib/selfService'

const money=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n)

export default function SelfServiceRequestEditor({row}:{row:SelfServiceRequest}){
 const router=useRouter(),[monthly,setMonthly]=useState(row.pricing.monthlyNet),[once,setOnce]=useState(row.pricing.oneTimeNet),[lv,setLv]=useState(row.lvItems),[internal,setInternal]=useState(row.pricing.internal),[busy,setBusy]=useState(''),[notice,setNotice]=useState('')
 const patchInternal=(key:keyof typeof internal,value:number)=>setInternal(current=>({...current,[key]:value}))
 async function save(recalculate=false,status=row.status){setBusy(recalculate?'calc':'save');setNotice('');const r=await fetch(`/api/self-service-requests/${row.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status,monthlyNet:monthly,oneTimeNet:once,lvItems:lv,internal,recalculate})});const j=await r.json();setBusy('');if(r.ok){setMonthly(j.request.pricing.monthlyNet);setInternal(j.request.pricing.internal);setNotice(recalculate?'Preis wurde aus den geänderten Kalkulationswerten neu berechnet.':'Änderungen gespeichert.');router.refresh()}else setNotice(j.error||'Speichern fehlgeschlagen.')}
 async function promote(){setBusy('crm');setNotice('');const r=await fetch(`/api/self-service-requests/${row.id}/promote`,{method:'POST'});const j=await r.json();setBusy('');setNotice(r.ok?'Interessent wurde im gesamten CRM angelegt bzw. aktualisiert.':j.error||'CRM-Übernahme fehlgeschlagen.');if(r.ok)router.refresh()}
 async function reissue(){setBusy('reissue');setNotice('');const r=await fetch(`/api/self-service-requests/${row.id}/reissue`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({monthlyNet:monthly,oneTimeNet:once,lvItems:lv,internal})});const j=await r.json();setBusy('');setNotice(r.ok?(j.draftCreated?'Neues Angebot wurde freigegeben. Der Gmail-Entwurf mit aktualisiertem PDF ist bereit zum Senden.':'Neues Angebot wurde freigegeben. '+(j.notice||'Den Kundenlink können Sie erneut versenden.')):j.error||'Erneutes Freigeben fehlgeschlagen.');if(r.ok)router.refresh()}
 return <article className="panel requestEditor"><div className="panelHead"><div><span className="eyebrow">{row.offerNumber}</span><h3>{row.answers.company}</h3><p>{row.answers.objectType} · {row.answers.areaSqm.toLocaleString('de-DE')} m² · {row.answers.address}</p></div><span className={`requestStatus ${row.status}`}>{row.status==='review'?'Prüfung nötig':row.status==='offered'?'Angebot aktiv':row.status==='accepted'?'Gewonnen':row.status==='rejected'?'Abgelehnt':'Eingegangen'}</span></div>
  <div className="requestFacts"><span><b>Leistung</b>{row.answers.serviceTypes.join(', ')}</span><span><b>Turnus</b>{row.answers.frequency} · {row.answers.weekdays.join(', ')||'Tage offen'}</span><span><b>Zeitfenster</b>{row.answers.timeWindow}</span><span><b>Verschmutzung</b>{row.answers.soilLevel}</span></div>
  <details open><summary>Interne Kalkulation & Override</summary><div className="calcEditGrid"><label>Stundensatz (€)<input type="number" min="0" step=".01" value={internal.hourlyRate} onChange={e=>patchInternal('hourlyRate',Number(e.target.value))}/></label><label>Produktivität (m²/h)<input type="number" min="1" step="1" value={internal.productivity} onChange={e=>patchInternal('productivity',Number(e.target.value))}/></label><label>Zeit pro Besuch (h)<input type="number" min="0" step=".01" value={internal.hoursPerVisit} onChange={e=>patchInternal('hoursPerVisit',Number(e.target.value))}/></label><label>Material pro Monat (€)<input type="number" min="0" step=".01" value={internal.materialMonthly} onChange={e=>patchInternal('materialMonthly',Number(e.target.value))}/></label><label>Fahrt/Rüsten pro Monat (€)<input type="number" min="0" step=".01" value={internal.travelSetupMonthly} onChange={e=>patchInternal('travelSetupMonthly',Number(e.target.value))}/></label><label>Zuschlag (%)<input type="number" min="0" max="100" step="1" value={Math.round(internal.surcharges*100)} onChange={e=>patchInternal('surcharges',Number(e.target.value)/100)}/></label><label>Marge (%)<input type="number" min="0" max="95" step="1" value={Math.round(internal.margin*100)} onChange={e=>patchInternal('margin',Number(e.target.value)/100)}/></label></div><div className="calcPriceRow"><label>Monatspreis netto (€)<input type="number" min="0" step=".01" value={monthly} onChange={e=>setMonthly(Number(e.target.value))}/></label><label>Einmalpreis netto (€)<input type="number" min="0" step=".01" value={once} onChange={e=>setOnce(Number(e.target.value))}/></label><button className="secondary" disabled={!!busy} onClick={()=>save(true)}>{busy==='calc'?'Berechne …':'Preis neu berechnen'}</button></div><small className="calcHint">Nach der Neuberechnung können Sie den fertigen Preis weiterhin manuell überschreiben.</small></details>
  <details><summary>Leistungsverzeichnis bearbeiten ({lv.length})</summary><div className="lvEditor">{lv.map((x,i)=><div key={x.id}><input value={x.activityLabel} onChange={e=>setLv(v=>v.map((a,n)=>n===i?{...a,activityLabel:e.target.value}:a))}/><input value={x.frequency.custom||x.frequency.preset} onChange={e=>setLv(v=>v.map((a,n)=>n===i?{...a,frequency:{preset:e.target.value,custom:''}}:a))}/><textarea rows={2} value={x.shortText} onChange={e=>setLv(v=>v.map((a,n)=>n===i?{...a,shortText:e.target.value}:a))}/></div>)}</div></details>
  {row.status==='accepted'&&<div className="wonBox"><b>✓ Online angenommen {row.acceptedAt&&new Date(row.acceptedAt).toLocaleString('de-DE')}</b></div>}{row.status==='rejected'&&row.rejection&&<div className="rejectedBox"><b>✕ Online abgelehnt {row.rejectedAt&&new Date(row.rejectedAt).toLocaleString('de-DE')}</b><span><strong>Grund:</strong> {row.rejection.reasonLabel}</span>{row.rejection.details&&<span><strong>Anmerkung:</strong> {row.rejection.details}</span>}</div>}
  <div className="requestActions"><button className="primary" disabled={!!busy} onClick={promote}>{busy==='crm'?'Übernehme …':row.crmSync?'CRM aktualisieren':'Ins CRM übernehmen'}</button><button className="secondary" disabled={!!busy} onClick={()=>save(false)}>{busy==='save'?'Speichere …':'Änderungen speichern'}</button>{row.status!=='accepted'&&row.status!=='rejected'&&<button className="primary" disabled={!!busy||lv.length===0||(monthly<=0&&once<=0)} onClick={()=>save(false,'offered')}>Prüfen & Angebot freigeben</button>}{row.status==='rejected'&&<button className="primary reissueButton" disabled={!!busy||lv.length===0||(monthly<=0&&once<=0)} onClick={reissue}>{busy==='reissue'?'Bereite Versand vor …':'Ändern & erneut versenden'}</button>}{row.status==='offered'&&<a className="secondary" target="_blank" href={`/angebot/${row.offerToken}`}>Kundenansicht öffnen</a>}</div>
  {row.crmSync&&<div className="crmLinks"><a href={`/leads/${row.crmSync.leadId}`}>Lead öffnen</a><a href={`/offers/${row.crmSync.offerId}`}>Angebot öffnen</a>{row.crmSync.customerObjectId&&<a href={`/customers/${row.crmSync.customerObjectId}`}>Kundenobjekt öffnen</a>}</div>}{notice&&<p className="actionNotice">{notice}</p>}
 </article>
}

