'use client'
import {useState} from 'react'
import {SERVICE_CATALOG,SERVICE_FREQUENCIES} from '@/lib/serviceCatalog'
import type {ServiceSpecificationItem} from '@/lib/types'
export default function ServiceSpecificationConfigurator({value,onChange}:{value:ServiceSpecificationItem[];onChange:(items:ServiceSpecificationItem[])=>void}){
 const [active,setActive]=useState(SERVICE_CATALOG[0].id),group=SERVICE_CATALOG.find(x=>x.id===active)||SERVICE_CATALOG[0]
 const selected=(id:string)=>value.find(x=>x.groupId===group.id&&x.activityId===id)
 function toggle(id:string){const activity=group.activities.find(x=>x.id===id)!,old=selected(id);onChange(old?value.filter(x=>x!==old):[...value,{id:`${group.id}:${id}`,groupId:group.id,groupLabel:group.label,groupIcon:group.icon,activityId:id,activityLabel:activity.label,activityIcon:activity.icon,shortText:activity.shortText,frequency:{preset:'1x/Woche'}}])}
 function setFrequency(id:string,preset:string){onChange(value.map(x=>x.groupId===group.id&&x.activityId===id?{...x,frequency:{preset,custom:preset==='freie Eingabe'?x.frequency.custom||'':undefined}}:x))}
 function setCustom(id:string,custom:string){onChange(value.map(x=>x.groupId===group.id&&x.activityId===id?{...x,frequency:{preset:'freie Eingabe',custom}}:x))}
 return <section className="lvConfigurator"><div className="lvIntro"><div><span className="eyebrow">LEISTUNGSVERZEICHNIS (LV)</span><h4>Leistungen konfigurieren</h4><p>Leistungsart auswählen → Tätigkeiten anklicken → Turnus festlegen.</p></div><strong>{value.length} ausgewählt</strong></div><div className="lvLayout"><nav className="lvGroups">{SERVICE_CATALOG.map(x=><button type="button" key={x.id} className={x.id===group.id?'active':''} onClick={()=>setActive(x.id)}><span>{x.icon}</span><span><b>{x.label}</b><small>{value.filter(v=>v.groupId===x.id).length||''}</small></span></button>)}</nav><div className="lvActivities"><header><span className="lvGroupIcon">{group.icon}</span><div><h5>{group.label}</h5><p>{group.description}</p></div></header>{group.activities.map(activity=>{const item=selected(activity.id);return <div className={`lvActivity ${item?'selected':''}`} key={activity.id}><label><input type="checkbox" checked={Boolean(item)} onChange={()=>toggle(activity.id)}/><span className="lvActivityIcon">{activity.icon||'✓'}</span><span><b>{activity.label}</b><small>{activity.shortText}</small></span></label>{item&&<div className="lvFrequency"><select value={item.frequency.preset} onChange={e=>setFrequency(activity.id,e.target.value)}>{SERVICE_FREQUENCIES.map(x=><option key={x}>{x}</option>)}</select>{item.frequency.preset==='freie Eingabe'&&<input autoFocus value={item.frequency.custom||''} onChange={e=>setCustom(activity.id,e.target.value)} placeholder="z. B. jeden 1. Montag"/>}</div>}</div>})}</div></div></section>
}

