'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'
import type {Lead} from '@/lib/types'
const types=['Büro','Arztpraxis','Hotel','Schule / Kita','Hausverwaltung / Treppenhaus','Industrie','Baustelle','Sonstiges']
const floors=['Fliesen','PVC / Linoleum','Parkett','Laminat','Teppich','Gemischt','Sonstiges']
export default function SiteSurveyForm({leads,initialLeadId}:{leads:Lead[];initialLeadId?:string}){
 const router=useRouter();const initial=leads.find(l=>l.id===(initialLeadId||leads[0]?.id));const [leadId,setLeadId]=useState(initial?.id||'');const [f,setF]=useState({objectName:initial?.company||'',objectType:initial?.sector||'Büro',address:initial?.address||initial?.city||'',areaSqm:0,frequencyPerWeek:5,hoursPerVisit:0,workers:1,windowAreaSqm:0,restrooms:0,kitchens:0,floorType:'Gemischt',accessWindow:'nach Absprache',startDate:'',notes:''});const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 function patch(k:string,v:any){setF(x=>({...x,[k]:v}))}function choose(id:string){setLeadId(id);const l=leads.find(x=>x.id===id);if(l)setF(x=>({...x,objectName:l.company,objectType:l.sector,address:l.address||l.city}))}
 async function save(){setBusy(true);setError('');const r=await fetch('/api/surveys',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({leadId,...f})});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error||'Fehler');return}router.push(`/offers?lead=${leadId}&survey=${j.survey.id}`);router.refresh()}
 return <section className="panel surveyForm"><div className="panelHead"><div><span className="eyebrow">OBJEKTBESICHTIGUNG</span><h3>Kalkulationsgrundlage erfassen</h3></div></div><div className="surveyGrid"><label>Lead<select value={leadId} onChange={e=>choose(e.target.value)}>{leads.map(l=><option key={l.id} value={l.id}>{l.company} · {l.city}</option>)}</select></label><label>Objektname<input value={f.objectName} onChange={e=>patch('objectName',e.target.value)}/></label><label>Objekttyp<select value={f.objectType} onChange={e=>patch('objectType',e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label className="span2">Objektadresse<input value={f.address} onChange={e=>patch('address',e.target.value)}/></label><label>Fläche m²<input type="number" min="0" value={f.areaSqm} onChange={e=>patch('areaSqm',Number(e.target.value))}/></label><label>Reinigungen / Woche<input type="number" min="0" step="0.5" value={f.frequencyPerWeek} onChange={e=>patch('frequencyPerWeek',Number(e.target.value))}/></label><label>Stunden / Einsatz<input type="number" min="0" step="0.25" value={f.hoursPerVisit} onChange={e=>patch('hoursPerVisit',Number(e.target.value))}/></label><label>Mitarbeiter<input type="number" min="1" value={f.workers} onChange={e=>patch('workers',Number(e.target.value))}/></label><label>Glasfläche m²<input type="number" min="0" value={f.windowAreaSqm} onChange={e=>patch('windowAreaSqm',Number(e.target.value))}/></label><label>Sanitärräume<input type="number" min="0" value={f.restrooms} onChange={e=>patch('restrooms',Number(e.target.value))}/></label><label>Küchen / Teeküchen<input type="number" min="0" value={f.kitchens} onChange={e=>patch('kitchens',Number(e.target.value))}/></label><label>Bodenart<select value={f.floorType} onChange={e=>patch('floorType',e.target.value)}>{floors.map(x=><option key={x}>{x}</option>)}</select></label><label>Zugangs-/Leistungszeit<input value={f.accessWindow} onChange={e=>patch('accessWindow',e.target.value)}/></label><label>Gewünschter Start<input type="date" value={f.startDate} onChange={e=>patch('startDate',e.target.value)}/></label><label className="span3">Besonderheiten / Notizen<textarea rows={4} value={f.notes} onChange={e=>patch('notes',e.target.value)}/></label></div>{error&&<p className="actionNotice">{error}</p>}<div className="offerSave"><button className="primary" disabled={!leadId||busy} onClick={save}>{busy?'Speichere …':'Speichern & kalkulieren →'}</button></div></section>
}
