'use client'
import {useState} from 'react'
import {useRouter} from 'next/navigation'

type Tender={id:string;title:string;buyer:string;city:string;deadline:string;cpv:string;url:string;score:number;service:string;source:string}

export default function TenderFinder(){
 const router=useRouter(),[location,setLocation]=useState('Berlin'),[radius,setRadius]=useState(50),[service,setService]=useState('Alle Reinigungsleistungen'),[busy,setBusy]=useState(false),[items,setItems]=useState<Tender[]>([]),[selected,setSelected]=useState<Record<string,boolean>>({}),[message,setMessage]=useState(''),[searched,setSearched]=useState(false)
 async function search(){setBusy(true);setMessage('');setSearched(true);const r=await fetch('/api/tenders/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({location,radius,service})});const d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.error||'Suche fehlgeschlagen.');setItems(d.tenders||[]);setSelected({})}
 async function importOne(t:Tender){const candidate={id:t.id,company:t.buyer,city:t.city||location,address:t.city,sector:'Öffentliche Vergabe',website:t.url,phone:'',source:'Ausschreibung',sourceId:t.id,score:t.score,service:t.service,potential:t.score>=85?'hoch':'mittel',reason:`Ausschreibung: ${t.title} · Frist ${new Date(t.deadline).toLocaleDateString('de-DE')}`,duplicate:false};const r=await fetch('/api/lead-finder/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({candidates:[candidate]})});const d=await r.json();setMessage(d.imported?'Ausschreibung wurde als Lead übernommen.':'Diese Ausschreibung ist bereits im CRM.');setSelected(v=>({...v,[t.id]:true}));router.refresh()}
 return <>
 <section className="panel tenderSearch"><div className="tenderFields"><label>Ort oder Region<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="z. B. Berlin"/></label><label>Umkreis<select value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value={25}>25 km</option><option value={50}>50 km</option><option value={100}>100 km</option><option value={200}>200 km</option></select></label><label>Reinigungsart<select value={service} onChange={e=>setService(e.target.value)}><option>Alle Reinigungsleistungen</option><option>Unterhalts- und Gebäudereinigung</option><option>Glasreinigung</option><option>Büroreinigung</option></select></label><button className="primary" onClick={search} disabled={busy}>{busy?'Suche läuft …':'Ausschreibungen suchen'}</button></div><p className="tenderHint"><b>Live-Suche:</b> Offizielle EU-Vergaben von TED. Weitere deutsche Vergabequellen werden schrittweise ergänzt.</p></section>
 {message&&<div className="resultMessage">{message}</div>}
 {items.length>0&&<section className="panel tenderResults"><div className="panelHead"><div><span className="eyebrow">PASSENDE AUSSCHREIBUNGEN</span><h3>{items.length} aktuelle Treffer · {location} + {radius} km</h3></div></div><div className="tenderList">{items.map(t=><article className="tenderRow" key={t.id}><div className="tenderScore">{t.score}</div><div><span className="tenderSource">{t.source} · CPV {t.cpv||'Reinigung'}</span><h4>{t.title}</h4><p><b>{t.buyer}</b> · {t.city||location}</p><small>Angebotsfrist: <b>{new Date(t.deadline).toLocaleDateString('de-DE')}</b></small></div><div className="tenderActions"><a className="secondary" href={t.url} target="_blank" rel="noreferrer">Ausschreibung öffnen</a><button className="primary" disabled={!!selected[t.id]} onClick={()=>importOne(t)}>{selected[t.id]?'Im CRM':'Als Lead übernehmen'}</button></div></article>)}</div></section>}
 {searched&&!busy&&!items.length&&!message&&<section className="panel finderEmpty"><div className="finderIcon">▧</div><h3>Keine aktuell offenen Treffer</h3><p>Vergrößere den Umkreis oder wähle alle Reinigungsleistungen. Neue Bekanntmachungen werden fortlaufend veröffentlicht.</p></section>}
 </>
}

