import {NextResponse} from 'next/server'
import {createActivity,createCustomerObject,createTask,getLead,getOffer,getSurvey,updateLead,updateOffer} from '@/lib/store'
import type {OfferStatus} from '@/lib/types'
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const offer=await getOffer(id);return offer?NextResponse.json({offer}):NextResponse.json({error:'Nicht gefunden.'},{status:404})}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){
 const {id}=await params;const current=await getOffer(id);if(!current)return NextResponse.json({error:'Angebot nicht gefunden.'},{status:404});const body=await req.json();const status=body.status as OfferStatus|undefined;const offer=await updateOffer(id,{status,title:body.title,validUntil:body.validUntil,items:body.items,notes:body.notes});if(!offer)return NextResponse.json({error:'Update fehlgeschlagen.'},{status:500})
 if(status&&status!==current.status){await createActivity({leadId:offer.leadId,type:'Angebot',direction:'intern',content:`Angebot ${offer.number}: ${current.status} → ${status}`,outcome:status});if(status==='Versendet'){await updateLead(offer.leadId,{status:'Angebot'});const due=new Date(Date.now()+5*86400000).toISOString();await createTask({leadId:offer.leadId,title:`Angebot ${offer.number} nachfassen`,type:'Angebot',dueAt:due,note:'Prüfen, ob das Angebot angekommen ist und Rückfragen bestehen.'})}if(status==='Angenommen'){await updateLead(offer.leadId,{status:'Kunde'});const lead=await getLead(offer.leadId);const survey=offer.surveyId?await getSurvey(offer.surveyId):undefined;if(lead){await createCustomerObject({leadId:offer.leadId,offerId:offer.id,surveyId:offer.surveyId,status:survey?.startDate&&new Date(survey.startDate)<=new Date()?'Aktiv':'Geplant',objectName:survey?.objectName||lead.company,objectType:survey?.objectType||lead.sector,address:survey?.address||lead.address||lead.city,service:lead.service,startDate:survey?.startDate,areaSqm:survey?.areaSqm||0,frequencyPerWeek:survey?.frequencyPerWeek||0,monthlyRevenue:offer.subtotalMonthly,oneTimeRevenue:offer.subtotalOneTime,contractTermMonths:12,noticePeriodMonths:3,notes:`Automatisch aus angenommenem Angebot ${offer.number} angelegt.`})}await createTask({leadId:offer.leadId,title:'Auftragsstart abstimmen',type:'Sonstiges',dueAt:new Date(Date.now()+86400000).toISOString(),note:`Angebot ${offer.number} angenommen. Leistungsstart, Objektübergabe und Einsatzplanung abstimmen.`})}if(status==='Abgelehnt'){await updateLead(offer.leadId,{status:'Qualifiziert'})}}
 return NextResponse.json({offer})
}
