import 'server-only'
import crypto from 'crypto'
import {promises as fs} from 'fs'
import path from 'path'
import {adminConfigured,adminRest} from './supabaseAdmin'
import type {OfferItem,ServiceSpecificationItem} from './types'

export const SERVICE_TYPES=['Unterhaltsreinigung','Büroreinigung','Glasreinigung','Bauendreinigung / Baureinigung','Industriereinigung'] as const
export type QuestionnaireAnswers={company:string;contactName:string;email:string;phone:string;objectType:string;address:string;areaSqm:number;serviceTypes:string[];weekdays:string[];frequency:string;timeWindow:string;floorTypes:string[];areas:string[];restrooms:number;kitchens:number;glassAreaSqm:number;staircases:number;elevators:number;specialAreas:string;soilLevel:'leicht'|'normal'|'stark';materials:'LUPENREIN'|'Kunde'|'gemischt';access:string;specialRequests:string;desiredStart?:string}
export type PricingResult={reviewMode:'instant'|'review';reason?:string;monthlyNet:number;oneTimeNet:number;internal:{hourlyRate:number;productivity:number;hoursPerVisit:number;materialMonthly:number;travelSetupMonthly:number;surcharges:number;margin:number}}
export type SelfServiceRequest={id:string;publicToken:string;offerToken:string;status:'submitted'|'review'|'offered'|'accepted';answers:QuestionnaireAnswers;lvItems:ServiceSpecificationItem[];offerItems:OfferItem[];pricing:PricingResult;offerNumber:string;validUntil:string;createdAt:string;updatedAt:string;acceptedAt?:string;acceptance?:{ip:string;userAgent:string;timestamp:string};internalActivity?:{type:string;text:string;createdAt:string};followUpTask?:{title:string;status:string;dueAt:string}}

const file=path.join(process.cwd(),'data','self-service-requests.json')
async function readLocal():Promise<SelfServiceRequest[]>{try{return JSON.parse(await fs.readFile(file,'utf8'))}catch{return []}}
async function writeLocal(rows:SelfServiceRequest[]){await fs.writeFile(file,JSON.stringify(rows,null,2),'utf8')}
function fromDb(x:any):SelfServiceRequest{return {id:String(x.id),publicToken:x.public_token,offerToken:x.offer_token,status:x.status,answers:x.responses,lvItems:x.generated_lv_items||[],offerItems:x.offer_items||[],pricing:x.pricing_result,offerNumber:x.offer_number,validUntil:x.valid_until,createdAt:x.created_at,updatedAt:x.updated_at,acceptedAt:x.accepted_at||undefined,acceptance:x.acceptance||undefined,internalActivity:x.internal_activity||undefined,followUpTask:x.follow_up_task||undefined}}
function dbRow(x:SelfServiceRequest){return {id:x.id,public_token:x.publicToken,offer_token:x.offerToken,status:x.status,responses:x.answers,generated_lv_items:x.lvItems,offer_items:x.offerItems,pricing_result:x.pricing,offer_number:x.offerNumber,valid_until:x.validUntil,created_at:x.createdAt,updated_at:x.updatedAt,accepted_at:x.acceptedAt||null,acceptance:x.acceptance||null}}

export function generateLv(a:QuestionnaireAnswers):ServiceSpecificationItem[]{
 const f={preset:a.frequency,custom:''};const rows:ServiceSpecificationItem[]=[];let n=0
 const add=(groupId:string,groupLabel:string,groupIcon:string,activityLabel:string,shortText:string,frequency=f)=>rows.push({id:`lv-${++n}`,groupId,groupLabel,groupIcon,activityId:`a-${n}`,activityLabel,shortText,frequency})
 if(a.serviceTypes.some(x=>x.includes('Unterhalt')||x.includes('Büro'))){add('allgemein','Allgemeine Bereiche','▦','Oberflächen und Mobiliar reinigen',`Freie Oberflächen, Mobiliar und Kontaktpunkte in ${a.areas.join(', ')||'den vereinbarten Bereichen'} reinigen.`);add('boden','Bodenreinigung','▰','Böden reinigen',`${a.floorTypes.join(', ')||'Bodenflächen'} gemäß Materialanforderung saugen, wischen bzw. pflegen.`)}
 if(a.restrooms>0)add('sanitaer','Sanitär','◫','Sanitärbereiche reinigen',`${a.restrooms} Sanitärbereich(e) hygienisch reinigen, Verbrauchsmaterial kontrollieren und Abfall entsorgen.`)
 if(a.kitchens>0)add('kueche','Küche / Teeküche','⌂','Küchenbereiche reinigen',`${a.kitchens} Küche(n)/Teeküche(n), Arbeitsflächen, Spülen und erreichbare Geräteaußenflächen reinigen.`)
 if(a.glassAreaSqm>0||a.serviceTypes.includes('Glasreinigung'))add('glas','Glasreinigung','◇','Glasflächen reinigen',`${a.glassAreaSqm||'Vereinbarte'} m² Glasflächen inklusive Rahmen nach Absprache reinigen.`,{preset:'nach Vereinbarung',custom:''})
 if(a.staircases>0)add('treppe','Treppenhaus','↗','Treppenhaus reinigen',`${a.staircases} Treppenhaus/Treppenhäuser inklusive Handläufe und Podeste reinigen.`)
 if(a.elevators>0)add('aufzug','Aufzüge','↕','Aufzüge reinigen',`${a.elevators} Aufzug/Aufzüge innen einschließlich Bedienelementen reinigen.`)
 if(a.specialAreas)add('sonder','Sonderflächen','✦','Sonderflächen bearbeiten',a.specialAreas,{preset:'nach Vereinbarung',custom:''})
 if(a.serviceTypes.some(x=>x.includes('Bau')))add('bau','Baureinigung','▧','Bauend- / Bauzwischenreinigung','Bauverschmutzungen, Staub, Etiketten und Schutzfolien im vereinbarten Umfang entfernen.',{preset:'einmalig',custom:''})
 if(a.serviceTypes.includes('Industriereinigung'))add('industrie','Industriereinigung','⚙','Industrieflächen reinigen','Produktionsnahe Flächen und Anlagenumfelder gemäß Sicherheits- und Objektvorgaben reinigen.',{preset:'nach Vereinbarung',custom:''})
 return rows
}
export function calculate(a:QuestionnaireAnswers):PricingResult{
 const frequencyMap:Record<string,number>={'1× pro Woche':1,'2× pro Woche':2,'3× pro Woche':3,'5× pro Woche':5,'täglich':6,'einmalig':0};const visits=frequencyMap[a.frequency]??1;const productivity=a.soilLevel==='stark'?130:a.soilLevel==='leicht'?230:180;const hourlyRate=39.5;const hours=Math.max(.75,a.areaSqm/productivity);const material=a.materials==='Kunde'?0:a.areaSqm*.045;const travel=visits*4.33*18;const surcharge=(a.timeWindow.toLowerCase().includes('nacht')||a.timeWindow.toLowerCase().includes('wochenende'))?.2:0;const margin=.18;const monthlyBase=hours*visits*4.33*hourlyRate+material+travel;const monthly=Math.round(monthlyBase*(1+surcharge)/(1-margin)*100)/100;const oneTime=a.serviceTypes.some(x=>x.includes('Bau')||x==='Glasreinigung')?Math.round(Math.max(220,(a.glassAreaSqm*3.2)+(a.serviceTypes.some(x=>x.includes('Bau'))?a.areaSqm*2.4:0))*100)/100:0;const complex=a.areaSqm>2500||a.soilLevel==='stark'||a.serviceTypes.includes('Industriereinigung')||Boolean(a.specialAreas.trim())
 return {reviewMode:complex?'review':'instant',reason:complex?'Komplexer Objektumfang – finale Freigabe nach fachlicher Prüfung.':undefined,monthlyNet:visits?monthly:0,oneTimeNet:oneTime,internal:{hourlyRate,productivity,hoursPerVisit:Math.round(hours*100)/100,materialMonthly:Math.round(material*100)/100,travelSetupMonthly:Math.round(travel*100)/100,surcharges:surcharge,margin}}
}
export async function createSelfServiceRequest(answers:QuestionnaireAnswers){const now=new Date().toISOString(),pricing=calculate(answers),id=crypto.randomUUID();const row:SelfServiceRequest={id,publicToken:crypto.randomBytes(20).toString('hex'),offerToken:crypto.randomBytes(24).toString('hex'),status:pricing.reviewMode==='instant'?'offered':'review',answers,lvItems:generateLv(answers),offerItems:[...(pricing.monthlyNet?[{id:'monthly',service:answers.serviceTypes[0]||'Reinigung',description:'Leistungen gemäß beigefügtem LV',quantity:1,unit:'Monatspauschale',unitPrice:pricing.monthlyNet,billing:'monatlich' as const}]:[]),...(pricing.oneTimeNet?[{id:'once',service:answers.serviceTypes.find(x=>x.includes('Bau'))||'Glasreinigung',description:'Leistungen gemäß beigefügtem LV',quantity:1,unit:'Pauschale',unitPrice:pricing.oneTimeNet,billing:'einmalig' as const}]:[])],pricing,offerNumber:`LR-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`,validUntil:new Date(Date.now()+14*86400000).toISOString().slice(0,10),createdAt:now,updatedAt:now}
 if(adminConfigured){const r=await adminRest('self_service_requests',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(dbRow(row))});if(!r.ok)throw new Error('Anfrage konnte nicht gespeichert werden.')}else{const rows=await readLocal();rows.unshift(row);await writeLocal(rows)}return row}
export async function getSelfServiceRequest(token:string,kind:'public'|'offer'='offer'){if(adminConfigured){const col=kind==='offer'?'offer_token':'public_token';const r=await adminRest(`self_service_requests?${col}=eq.${encodeURIComponent(token)}&select=*&limit=1`);if(!r.ok)return undefined;const rows=await r.json() as any[];return rows[0]?fromDb(rows[0]):undefined}return (await readLocal()).find(x=>(kind==='offer'?x.offerToken:x.publicToken)===token)}
export async function acceptSelfServiceOffer(token:string,meta:{ip:string;userAgent:string}){const row=await getSelfServiceRequest(token);if(!row||row.status!=='offered')return undefined;const timestamp=new Date().toISOString();row.status='accepted';row.acceptedAt=timestamp;row.updatedAt=timestamp;row.acceptance={...meta,timestamp};row.internalActivity={type:'Angebotsannahme',text:`Angebot ${row.offerNumber} wurde online angenommen.`,createdAt:timestamp};row.followUpTask={title:`Neukundenkontakt: ${row.answers.company}`,status:'Offen',dueAt:new Date(Date.now()+86400000).toISOString()};if(adminConfigured){const r=await adminRest(`self_service_requests?id=eq.${row.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:row.status,accepted_at:timestamp,updated_at:timestamp,acceptance:row.acceptance,internal_activity:row.internalActivity,follow_up_task:row.followUpTask})});if(!r.ok)throw new Error('Annahme konnte nicht gespeichert werden.')}else{const rows=await readLocal();const i=rows.findIndex(x=>x.id===row.id);rows[i]=row;await writeLocal(rows)}return row}

