import {NextResponse} from 'next/server'
import {updateSelfServiceRequest} from '@/lib/selfService'
import {buildOfferPdf} from '@/lib/pdf'
import {createGmailDraftWithPdf,gmailConfigured} from '@/lib/gmail'
import {COMPANY} from '@/lib/company'
import type {Lead,Offer,SiteSurvey} from '@/lib/types'

export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params,b=await req.json();const row=await updateSelfServiceRequest(id,{status:'offered',monthlyNet:Number(b.monthlyNet),oneTimeNet:Number(b.oneTimeNet),lvItems:Array.isArray(b.lvItems)?b.lvItems:undefined,internal:b.internal&&typeof b.internal==='object'?b.internal:undefined});if(!row)return NextResponse.json({error:'Kundenanfrage wurde nicht gefunden.'},{status:404});if(!gmailConfigured)return NextResponse.json({reissued:true,draftCreated:false,offerUrl:`/angebot/${row.offerToken}`,notice:'Gmail ist noch nicht autorisiert; der aktualisierte Kundenlink ist wieder aktiv.'});const lead:Lead={id:row.id,company:row.answers.company,contact:row.answers.contactName,email:row.answers.email,phone:row.answers.phone,city:row.answers.address,sector:row.answers.objectType,score:100,service:row.answers.serviceTypes.join(', '),status:'Angebot',reason:'Self-Service-Anfrage',potential:'hoch',address:row.answers.address,createdAt:row.createdAt};const offer:Offer={id:row.id,leadId:row.id,number:row.offerNumber,title:`Überarbeitetes Reinigungsangebot · ${row.answers.objectType}`,status:'Versendet',validUntil:row.validUntil,items:row.offerItems,serviceSpecification:{version:1,items:row.lvItems},notes:'Die angebotenen Leistungen erfolgen gemäß Absprache und beigefügtem Leistungsverzeichnis (LV).',subtotalOneTime:row.pricing.oneTimeNet,subtotalMonthly:row.pricing.monthlyNet,vatRate:19,createdAt:row.createdAt};const survey:SiteSurvey={id:row.id,leadId:row.id,status:'Kalkuliert',objectName:row.answers.company,objectType:row.answers.objectType,address:row.answers.address,areaSqm:row.answers.areaSqm,frequencyPerWeek:0,hoursPerVisit:row.pricing.internal.hoursPerVisit,workers:1,windowAreaSqm:row.answers.glassAreaSqm,restrooms:row.answers.restrooms,kitchens:row.answers.kitchens,floorType:row.answers.floorTypes.join(', '),accessWindow:row.answers.timeWindow,createdAt:row.createdAt};const pdf=await buildOfferPdf(offer,lead,survey);const origin=new URL(req.url).origin,greeting=row.answers.contactName?`Guten Tag ${row.answers.contactName},`:'Guten Tag,';const message=`${greeting}\n\nvielen Dank für Ihre Rückmeldung. Wir haben unser Angebot ${row.offerNumber} für Sie überarbeitet.\n\nDas aktualisierte Angebot können Sie hier ansehen und direkt annehmen:\n${origin}/angebot/${row.offerToken}\n\nDas neue Angebot mit Leistungsverzeichnis finden Sie zusätzlich im PDF-Anhang.\n\nFreundliche Grüße\n${COMPANY.name}\n${COMPANY.phone}\n${COMPANY.email}`;await createGmailDraftWithPdf(row.answers.email,`Überarbeitetes Angebot ${row.offerNumber} | ${COMPANY.name}`,message,`${row.offerNumber}-ueberarbeitet.pdf`,pdf);return NextResponse.json({reissued:true,draftCreated:true,offerUrl:`/angebot/${row.offerToken}`})}catch(e:any){return NextResponse.json({error:e?.message||'Angebot konnte nicht erneut vorbereitet werden.'},{status:500})}}

