create table if not exists public.website_visitors (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'webhook',
  provider_visit_id text not null,
  company text not null,
  domain text,
  city text,
  country text,
  industry text,
  pages jsonb not null default '[]'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  visits integer not null default 1 check (visits > 0),
  intent_score integer not null default 0 check (intent_score between 0 and 100),
  status text not null default 'Neu' check (status in ('Neu','Übernommen','Ignoriert')),
  lead_id bigint references public.leads(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (owner_id,provider,provider_visit_id)
);

create index if not exists website_visitors_owner_last_seen_idx on public.website_visitors(owner_id,last_seen_at desc);
alter table public.website_visitors enable row level security;
grant select,insert,update,delete on public.website_visitors to authenticated;
grant usage,select on sequence public.website_visitors_id_seq to authenticated;
create policy "website_visitors_select_own" on public.website_visitors for select to authenticated using ((select auth.uid()) = owner_id);
create policy "website_visitors_insert_own" on public.website_visitors for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy "website_visitors_update_own" on public.website_visitors for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy "website_visitors_delete_own" on public.website_visitors for delete to authenticated using ((select auth.uid()) = owner_id);

